version: 2
updates:
- package-ecosystem: docker
  directory: "/tests/dependabot"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: nuget
  directory: "/tests"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: development
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: development
