language: csharp
mono: none
dotnet: 2.1

services:
  - docker

before_install:
- docker pull qlikcore/engine:12.329.0
- docker run -d -p 127.0.0.1:4848:9076 qlikcore/engine:12.329.0 -S AcceptEULA=yes
- docker ps -a

script:
  - dotnet --info
  - cd ./tests
  - dotnet restore
  - dotnet test -p:noGitVersionTask=1
