language: csharp
mono: none
dotnet: 2.1
script:
  - dotnet --info
  - dotnet restore ./examples/SenseDesktop
  - dotnet build ./examples/SenseDesktop
  - dotnet run ./examples/SenseDesktop/bin/Release/netcoreapp2.1/SenseDesktop.dll
