trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
#- job: Linux
#  pool:
#    vmImage: 'ubuntu-16.04'
#  steps:
#  - script: echo hello from Linux
#- job: macOS
#  pool:
#    vmImage: 'macOS-10.13'
#  steps:
#  - script: echo hello from macOS

# Run a build on Windows at the same time
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - task: DotNetCoreInstaller@0
      inputs:
         packageType: sdk
         version: 2.2.105

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore $(buildConfiguration)'
      inputs:
        command: restore
        projects: '**/*tests/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: build
        projects: '**/*tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)