name: CI

on: [push, pull_request]

jobs:
  build:
    name: test against qlik-core
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        cd tests
        docker build --tag qlikcoreengine:latest dependabot/.
        docker-compose up -d
        dotnet restore
        dotnet test
        docker-compose down


